# Generated by Django 4.1.7 on 2023-03-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.IntegerField(null=True)),
                ('vk_uid', models.IntegerField(null=True)),
                ('used', models.BooleanField(null=True)),
                ('citi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_bot.citi')),
            ],
        ),
    ]
