# Generated by Django 4.1.7 on 2023-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_bot', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=40, null=True)),
                ('next_stage', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('vk_uid', models.IntegerField(null=True)),
                ('stage', models.CharField(default='menu', max_length=100, null=True)),
                ('used_citi', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='citi',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='citi',
            name='name',
        ),
        migrations.AddField(
            model_name='citi',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
