# Generated by Django 4.1.7 on 2023-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_bot', '0003_stage_user_remove_game_citi_delete_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_citi',
            field=models.TextField(default=''),
        ),
    ]
